// @generated by protoc-gen-es v1.2.0
// @generated from file node/v1/node.proto (package node.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message node.v1.NodeTypeRequest
 */
export const NodeTypeRequest = proto3.makeMessageType(
  "node.v1.NodeTypeRequest",
  [],
);

/**
 * @generated from message node.v1.NodeTypeResponse
 */
export const NodeTypeResponse = proto3.makeMessageType(
  "node.v1.NodeTypeResponse",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "result", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

