// @generated by protoc-gen-es v1.2.0
// @generated from file v1/helloworld.proto (package helloworld.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message helloworld.v1.SayHelloRequest
 */
export const SayHelloRequest = proto3.makeMessageType(
  "helloworld.v1.SayHelloRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message helloworld.v1.SayHelloResponse
 */
export const SayHelloResponse = proto3.makeMessageType(
  "helloworld.v1.SayHelloResponse",
  () => [
    { no: 1, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

