// @generated by protoc-gen-es v1.2.0
// @generated from file v1/helloworld.proto (package helloworld.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message helloworld.v1.SayHelloRequest
 */
export declare class SayHelloRequest extends Message<SayHelloRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  constructor(data?: PartialMessage<SayHelloRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "helloworld.v1.SayHelloRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SayHelloRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SayHelloRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SayHelloRequest;

  static equals(a: SayHelloRequest | PlainMessage<SayHelloRequest> | undefined, b: SayHelloRequest | PlainMessage<SayHelloRequest> | undefined): boolean;
}

/**
 * @generated from message helloworld.v1.SayHelloResponse
 */
export declare class SayHelloResponse extends Message<SayHelloResponse> {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  constructor(data?: PartialMessage<SayHelloResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "helloworld.v1.SayHelloResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SayHelloResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SayHelloResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SayHelloResponse;

  static equals(a: SayHelloResponse | PlainMessage<SayHelloResponse> | undefined, b: SayHelloResponse | PlainMessage<SayHelloResponse> | undefined): boolean;
}

