import './globals.css'
import { Poppins } from 'next/font/google'
import Nav from '@/components/layout/Nav'

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ background: 'black' }}>
      <body>
        <main className={`flex flex-col min-h-screen ${poppins.className}`}>
          <Nav />
          <div>{children}</div>
        </main>
      </body>
    </html>
  )
}
