import './globals.css'
import { Inter } from 'next/font/google'
import Nav from '@/components/layout/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className={` min-h-screen ${inter.className}`}>
          <Nav />
          <div>
            <h6 className="text-3xl font-bold ">{children}</h6>
          </div>
        </main>
      </body>
    </html>
  )
}
